// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

// Build the complete Swagger documentation by combining all parts
const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "title": "Restaurant Management API",
    "description": "A Restaurant Management API built using Go",
    "version": "1.0.0",
    "contact": {
      "email": "yzakariyahali100@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "localhost:8001",
  "basePath": "/api/v1",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "description": "Enter the token with the Bearer prefix, e.g. 'Bearer abcde12345'"
    }
  },
  "paths": {` + systemPaths + authPaths + usersPaths + restaurantsPaths + menusPaths + `},` + definitions + `,` + tags + `}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8001",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Restaurant Management API",
	Description:      "A Restaurant Management API built using Go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
