// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"


const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "title": "Restaurant Management API",
    "description": "A Restaurant Management API built using Go",
    "version": "1.0.0",
    "contact": {
      "email": "your.email@example.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "localhost:3000",
  "basePath": "/api/v1",
	"schemes": [
		"http"
	],
	"consumes": [
		"application/json"
	],
	"produces": [
		"application/json"
	],
	"securityDefinitions": {
		"Bearer": {
			"type": "apiKey",
			"name": "Authorization",
			"in": "header",
			"description": "Enter the token with the Bearer prefix, e.g. 'Bearer abcde12345'"
		}
	},
		"paths": {
			"/healthcheck": {
				"get": {
					"tags": [
						"system"
					],
					"summary": "API Health Check",
					"description": "Returns the health status of the API",
					"operationId": "healthCheck",
					"responses": {
						"200": {
							"description": "API is healthy",
							"schema": {
								"type": "object",
								"properties": {
									"title": {
										"type": "string",
										"example": "Success"
									},
									"message": {
										"type": "string",
										"example": "API is healthy and running"
									}
								},
								"required": [
									"title",
									"message"
								]
							}
						}
					}
				}
			},
			"/users": {
			"get": {
				"tags": [
					"Users"
				],
				"summary": "List all users",
				"description": "Returns a list of users in the system",
				"operationId": "listUsers",
				"security": [
					{
						"Bearer": []
					}
				],
				"responses": {
					"200": {
						"description": "Successful operation",
										"schema": {
											"type": "object",
											"properties": {
												"title": { "type": "string", "example": "Success" },
												"data": { "type": "array", "items": { "$ref": "#/definitions/User" } }
											},
											"required": ["title","data"]
										}
					},
					"401": {
						"description": "Unauthorized",
						"schema": {
							"$ref": "#/definitions/Error"
						}
					},
					"500": {
						"description": "Internal server error",
						"schema": {
							"$ref": "#/definitions/Error"
						}
					}
				}
			},
			"post": {
				"tags": [
					"Users"
				],
				"summary": "Create a new user",
				"description": "Creates a new user in the system",
				"operationId": "createUser",
				"parameters": [
					{
						"in": "body",
						"name": "user",
						"description": "User object that needs to be created",
						"required": true,
						"schema": {
							"$ref": "#/definitions/UserInput"
						}
					}
				],
				"responses": {
					"201": {
						"description": "User created successfully",
						"schema": {
							"$ref": "#/definitions/User"
						}
					},
					"400": {
						"description": "Invalid input",
						"schema": {
							"$ref": "#/definitions/Error"
						}
					},
					"500": {
						"description": "Internal server error",
						"schema": {
							"$ref": "#/definitions/Error"
						}
					}
				}
			}
		},
		"/users/{id}": {
			"get": {
				"tags": [
					"Users"
				],
				"summary": "Get user by ID",
				"description": "Returns a single user",
				"operationId": "getUser",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of user to return",
						"required": true,
						"type": "string"
					}
				],
				"responses": {
					"200": {
						"description": "Successful operation",
						"schema": {
							"$ref": "#/definitions/User"
						}
					},
					"404": {
						"description": "User not found",
						"schema": {
							"$ref": "#/definitions/Error"
						}
					},
					"500": {
						"description": "Internal server error",
						"schema": {
							"$ref": "#/definitions/Error"
						}
					}
				}
			}
		},
		"/restaurants": {
			"get": {
				"tags": [
					"Restaurants"
				],
				"summary": "List all restaurants",
				"description": "Returns a list of restaurants",
				"operationId": "listRestaurants",
				"responses": {
					"200": {
						"description": "Successful operation",
						"schema": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/Restaurant"
							}
						}
					},
					"500": {
						"description": "Internal server error",
						"schema": {
							"$ref": "#/definitions/Error"
						}
					}
				}
			},
			"post": {
				"tags": [
					"Restaurants"
				],
				"summary": "Create a new restaurant",
				"description": "Adds a new restaurant to the system",
				"operationId": "createRestaurant",
				"security": [
					{
						"Bearer": []
					}
				],
				"parameters": [
					{
						"in": "body",
						"name": "restaurant",
						"description": "Restaurant object that needs to be created",
						"required": true,
						"schema": {
							"$ref": "#/definitions/RestaurantInput"
						}
					}
				],
				"responses": {
					"201": {
						"description": "Restaurant created successfully",
						"schema": {
							"$ref": "#/definitions/Restaurant"
						}
					},
					"400": {
						"description": "Invalid input",
						"schema": {
							"$ref": "#/definitions/Error"
						}
					},
					"401": {
						"description": "Unauthorized",
						"schema": {
							"$ref": "#/definitions/Error"
						}
					},
					"500": {
						"description": "Internal server error",
						"schema": {
							"$ref": "#/definitions/Error"
						}
					}
				}
			}
		}
	},
	"definitions": {
		"User": {
			"type": "object",
			"properties": {
				"id": {
					"type": "string",
					"format": "uuid"
				},
				"name": {
					"type": "string"
				},
				"email": {
					"type": "string",
					"format": "email"
				},
				"created_at": {
					"type": "string",
					"format": "date-time"
				},
				"updated_at": {
					"type": "string",
					"format": "date-time"
				}
			},
			"required": [
				"id",
				"name",
				"email"
			]
		},
		"UserInput": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"minLength": 2,
					"maxLength": 50
				},
				"email": {
					"type": "string",
					"format": "email"
				},
				"password": {
					"type": "string",
					"format": "password",
					"minLength": 8
				}
			},
			"required": [
				"name",
				"email",
				"password"
			]
		},
		"Restaurant": {
			"type": "object",
			"properties": {
				"id": {
					"type": "string",
					"format": "uuid"
				},
				"name": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"address": {
					"type": "string"
				},
				"cuisine_type": {
					"type": "string"
				},
				"rating": {
					"type": "number",
					"format": "float",
					"minimum": 0,
					"maximum": 5
				},
				"created_at": {
					"type": "string",
					"format": "date-time"
				},
				"updated_at": {
					"type": "string",
					"format": "date-time"
				}
			},
			"required": [
				"id",
				"name",
				"address"
			]
		},
		"RestaurantInput": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"minLength": 2,
					"maxLength": 100
				},
				"description": {
					"type": "string",
					"maxLength": 500
				},
				"address": {
					"type": "string",
					"minLength": 5,
					"maxLength": 200
				},
				"cuisine_type": {
					"type": "string"
				}
			},
			"required": [
				"name",
				"address"
			]
		},
		"Error": {
			"type": "object",
			"properties": {
				"title": {
					"type": "string"
				},
				"message": {
					"type": "string"
				}
			},
			"required": [
				"title",
				"message"
			]
		}
	},
	"tags": [
		{
			"name": "Users",
			"description": "Operations about users"
		},
		{
			"name": "Restaurants",
			"description": "Operations about restaurants"
		},
		{
			"name": "Auth",
			"description": "Authentication operations"
		}
	]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "http://localhost:3000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Restaurant Management API",
	Description:      "A Restaurant Management API built using Go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
